export type DrugRoute = { group: string; id: string };

export const GENERATED_DRUG_LINK_MAP: Record<string, DrugRoute> = {
  "Amoxicillin": { group: "antibiotic", id: "amoxicillin" },
  "Oxytetracycline": { group: "antibiotic", id: "oxytetracycline" },
  "Oxytetracycline LA": { group: "antibiotic", id: "oxytetracycline_la" },
  "Doxycycline": { group: "antibiotic", id: "doxycycline" },
  "Florfenicol": { group: "antibiotic", id: "florfenicol" },
  "Enrofloxacin": { group: "antibiotic", id: "enrofloxacin" },
  "Tylosin": { group: "antibiotic", id: "tylosin" },
  "Tilmicosin": { group: "antibiotic", id: "tilmicosin" },
  "Colistin": { group: "antibiotic", id: "colistin" },
  "Ceftiofur": { group: "antibiotic", id: "ceftiofur" },
  "Sulfa_trimethoprim": { group: "antibiotic", id: "sulfamethoxazole_tmp" },
  "Tulathromycin": { group: "antibiotic", id: "tulathromycin" },
  "Azithromycin": { group: "antibiotic", id: "azithromycin" },
  "Spiramycin": { group: "antibiotic", id: "spiramycin" },
  "Josamycin": { group: "antibiotic", id: "josamycin" },
  "Lincomycin": { group: "antibiotic", id: "lincomycin" },
  "Spectinomycin": { group: "antibiotic", id: "spectinomycin" },
  "Neomycin": { group: "antibiotic", id: "neomycin" },
  "Gentamicin": { group: "antibiotic", id: "gentamicin" },
  "Kanamycin": { group: "antibiotic", id: "kanamycin" },
  "Amikacin": { group: "antibiotic", id: "amikacin" },
  "Tetracycline": { group: "antibiotic", id: "tetracycline" },
  "Oxolinic acid": { group: "antibiotic", id: "oxolinic_acid" },
  "Ciprofloxacin": { group: "antibiotic", id: "ciprofloxacin" },
  "Norfloxacin": { group: "antibiotic", id: "norfloxacin" },
  "Levofloxacin": { group: "antibiotic", id: "levofloxacin" },
  "Nalidixic acid": { group: "antibiotic", id: "nalidixic_acid" },
  "Oxolinic acid (phối hợp)": { group: "antibiotic", id: "oxolinic_acid_plus" },
  "Spiramycin + Tylosin": { group: "antibiotic", id: "spiramycin_tylo" },
  "Danofloxacin": { group: "antibiotic", id: "danofloxacin" },
  "Marbofloxacin": { group: "antibiotic", id: "marbofloxacin" },
  "Difloxacin": { group: "antibiotic", id: "difloxacin" },
  "Flumequine": { group: "antibiotic", id: "flumequine" },
  "Cephalexin": { group: "antibiotic", id: "cephalexin" },
  "Cefaclor": { group: "antibiotic", id: "cefaclor" },
  "Amoxiclav": { group: "antibiotic", id: "amoxiclav" },
  "Cefquinome": { group: "antibiotic", id: "cefquinome" },
  "Penicillin": { group: "antibiotic", id: "penicillin" },
  "Ampicillin": { group: "antibiotic", id: "ampicillin" },
  "Tiamulin": { group: "antibiotic", id: "tiamulin" },
  "Metronidazole": { group: "antibiotic", id: "metronidazole" },
  "Flunixin": { group: "antiinflammatory_analgesic", id: "Flunixin" },
  "Meloxicam": { group: "antiinflammatory_analgesic", id: "meloxicam" },
  "Ketoprofen": { group: "antiinflammatory_analgesic", id: "ketoprofen" },
  "Diclofenac": { group: "antiinflammatory_analgesic", id: "diclofenac" },
  "Paracetamol": { group: "antiinflammatory_analgesic", id: "paracetamol" },
  "Aspirin": { group: "antiinflammatory_analgesic", id: "aspirin" },
  "Ibuprofen": { group: "antiinflammatory_analgesic", id: "ibuprofen" },
  "Metamizole (Anagin)": { group: "antiinflammatory_analgesic", id: "anagin" },
  "Itraconazole": { group: "antiinflammatory_analgesic", id: "itraconazole" },
  "Ketoconazole": { group: "antiinflammatory_analgesic", id: "ketoconazole" },
  "Clotrimazole": { group: "antiinflammatory_analgesic", id: "clotrimazole" },
  "Oresol (điện giải uống)": { group: "electrolyte", id: "oresol" },
  "Glucose": { group: "electrolyte", id: "glucose" },
  "Điện giải tổng hợp (Na/K/Cl)": { group: "electrolyte", id: "electrolyte_mix" },
  "Vitamin C điện giải": { group: "electrolyte", id: "vitamin_c_electrolyte" },
  "B-complex + Điện giải": { group: "electrolyte", id: "bcomplex_electrolyte" },
  "Calcium borogluconate": { group: "electrolyte", id: "calcium_borogluconate" },
  "Calcium gluconate": { group: "electrolyte", id: "calcium_gluconate" },
  "Mineral solution": { group: "electrolyte", id: "mineral_solution" },
  "Vitamin BC": { group: "vitamin_tonic", id: "vitamin_bc" },
  "Multivitamin tổng hợp": { group: "vitamin_tonic", id: "multivitamin" },
  "Vitamin ADE": { group: "vitamin_tonic", id: "vitamin_ade" },
  "Vitamin C": { group: "vitamin_tonic", id: "vitamin_c" },
  "Vitamin E - Selenium": { group: "vitamin_tonic", id: "vitamin_e_selenium" },
  "Vitamin B1": { group: "vitamin_tonic", id: "b1" },
  "Vitamin B12": { group: "vitamin_tonic", id: "b12" },
  "Vitamin K": { group: "vitamin_tonic", id: "vitamin_k" },
  "Choline chloride": { group: "vitamin_tonic", id: "choline_chloride" },
  "Sorbitol + Acid amin": { group: "vitamin_tonic", id: "sorbitol_amino" },
  "Hepetol (bổ gan - giải độc)": { group: "vitamin_tonic", id: "hepetol" },
  "ATP (tăng lực - phục hồi)": { group: "vitamin_tonic", id: "atp" },
  "Calcium - Magnesium - B6": { group: "vitamin_tonic", id: "calcium_mag_b6" },
  "Calcium - D3 (xương - sinh sản)": { group: "vitamin_tonic", id: "calcium_d3" },
  "Amino peptide phục hồi": { group: "vitamin_tonic", id: "amino_peptide" },
  "Điện giải + Amino acid": { group: "vitamin_tonic", id: "electrolyte_amino_premium" },
  "Bổ gan + thận tổng hợp": { group: "vitamin_tonic", id: "liver_kidney_tonic" },
  "Butafosfan + B12 (tăng lực - phục hồi)": { group: "vitamin_tonic", id: "butafosfan_b12" },
  "Khoáng premix trộn thức ăn": { group: "vitamin_tonic", id: "mineral_premix_feed" },
  "Albendazole": { group: "antiparasitic_internal", id: "albendazole" },
  "Fenbendazole": { group: "antiparasitic_internal", id: "fenbendazole" },
  "Levamisole": { group: "antiparasitic_internal", id: "levamisole" },
  "Ivermectin": { group: "antiparasitic_internal", id: "ivermectin" },
  "Doramectin": { group: "antiparasitic_internal", id: "doramectin" },
  "Praziquantel": { group: "antiparasitic_internal", id: "praziquantel" },
  "Closantel": { group: "antiparasitic_internal", id: "closantel" },
  "Oxyclozanide": { group: "antiparasitic_internal", id: "oxyclozanide" },
  "Triclabendazole": { group: "antiparasitic_internal", id: "triclabendazole" },
  "Toltrazuril": { group: "antiparasitic_internal", id: "toltrazuril" },
  "Diclazuril": { group: "antiparasitic_internal", id: "diclazuril" },
  "Niclosamide": { group: "antiparasitic_internal", id: "niclosamide" },
  "Amprolium": { group: "antiparasitic_internal", id: "amprolium" },
  "Moxidectin": { group: "antiparasitic_internal", id: "moxidectin" },
  "Permethrin": { group: "antiparasitic_external", id: "permethrin" },
  "Cypermethrin": { group: "antiparasitic_external", id: "cypermethrin" },
  "Deltamethrin": { group: "antiparasitic_external", id: "deltamethrin" },
  "Amitraz": { group: "antiparasitic_external", id: "amitraz" },
  "Fipronil": { group: "antiparasitic_external", id: "fipronil" },
  "Imidacloprid": { group: "antiparasitic_external", id: "imidacloprid" },
  "Fluralaner": { group: "antiparasitic_external", id: "fluralaner" },
  "Bromhexine": { group: "respiratory_support", id: "bromhexine" },
  "Eucalyptus oil": { group: "respiratory_support", id: "eucalyptus" },
  "Menthol - Camphor": { group: "respiratory_support", id: "menthol_camphor" },
  "Guaifenesin (long đờm)": { group: "respiratory_support", id: "guaifenesin" },
  "Dung dịch thông mũi": { group: "respiratory_support", id: "nasal_decongestant" },
  "Ambroxol": { group: "respiratory_support", id: "ambroxol" },
  "Probiotic (men vi sinh)": { group: "digestive_support", id: "probiotic" },
  "Enzyme tiêu hoá": { group: "digestive_support", id: "enzyme_mix" },
  "Pectin - Kaolin": { group: "digestive_support", id: "pectin_kaolin" },
  "Men tiêu hoá + Vitamin": { group: "digestive_support", id: "digestive_vitamin" },
  "Than hoạt tính (giải độc tiêu hoá)": { group: "digestive_support", id: "activated_charcoal" },
  "Simethicone": { group: "digestive_support", id: "simethicone" },
  "Dầu paraffin": { group: "digestive_support", id: "liquid_paraffin" },
  "Dimethicone": { group: "digestive_support", id: "dimethicone" },
  "Sodium bicarbonate": { group: "digestive_support", id: "sodium_bicarbonate" },
  "Acetic acid": { group: "digestive_support", id: "acetic_acid" },
  "Clostridium antitoxin": { group: "digestive_support", id: "clostridium_antitoxin" },
  "Diminazene (Azidin)": { group: "blood_parasite", id: "azidin" },
  "Imidocarb": { group: "blood_parasite", id: "imidocarb" },
  "Buparvaquone (trị Theileria)": { group: "blood_parasite", id: "buparvaquone" },
  "Oxytocin": { group: "hormone", id: "oxytocin" },
  "Povidone-iodine": { group: "disinfectant_hygiene", id: "povidone_iodine" },
  "Iodophor (iod sát trùng)": { group: "disinfectant_hygiene", id: "iodophor" },
  "Chlorine / Cloramin": { group: "disinfectant_hygiene", id: "chlorine_compound" },
  "Chlorine dioxide": { group: "disinfectant_hygiene", id: "chlorine_dioxide" },
  "Benzalkonium chloride": { group: "disinfectant_hygiene", id: "benzalkonium_chloride" },
  "Glutaraldehyde": { group: "disinfectant_hygiene", id: "glutaraldehyde" },
  "Vôi bột": { group: "disinfectant_hygiene", id: "lime_powder" },
  "Chế phẩm sinh học sát trùng": { group: "disinfectant_hygiene", id: "bio_disinfectant" },
  "Vacxin PPR": { group: "vaccine", id: "ppr_vaccine" },
  "Vacxin Tụ huyết trùng": { group: "vaccine", id: "pasteurella_vaccine" },
  "Caffeine": { group: "stimulant", id: "caffeine" },
  "Camphor": { group: "stimulant", id: "camphor" },
  "Nikethamide": { group: "stimulant", id: "nikethamide" },
  "Strychnine": { group: "stimulant", id: "strychnine" },
  "Atropine": { group: "stimulant", id: "atropine" },
};
