// scripts/buildDrugRegistry.js
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const DRUGS_DIR = path.join(ROOT, "app", "data", "drugs");
const OUTPUT_DIR = path.join(ROOT, "src", "generated");
const OUTPUT_FILE = path.join(OUTPUT_DIR, "drugRegistry.ts");

function buildDrugRegistry() {
  const groups = fs
    .readdirSync(DRUGS_DIR)
    .filter((name) => {
      const full = path.join(DRUGS_DIR, name);
      return fs.statSync(full).isDirectory() && name !== "group";
    });

  const entries = [];

  for (const group of groups) {
    const groupDir = path.join(DRUGS_DIR, group);
    const files = fs
      .readdirSync(groupDir)
      .filter(
        (f) =>
          f.endsWith(".json") &&
          f !== "list.json" // bỏ list, chỉ lấy file chi tiết
      );

    for (const file of files) {
      const id = file.replace(/\.json$/, "");
      const key = `${group}/${id}`;
      // đường dẫn từ src/generated → app/data/drugs/...
      const requirePath = `../../app/data/drugs/${group}/${file}`;

      entries.push(
        `  "${key}": () => require("${requirePath}")`
      );
    }
  }

  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  const content = `// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by scripts/buildDrugRegistry.js

export const drugRegistry: Record<string, () => any> = {
${entries.join(",\n")}
};
`;

  fs.writeFileSync(OUTPUT_FILE, content, "utf8");
  console.log(
    `✅ Generated drugRegistry.ts with ${entries.length} entries.`
  );
}

buildDrugRegistry();
